### ISSUE TITLE
Component first render through preact router causes node was deleted

### ISSUE THREAD

**Issue by yannick1691** [webgem-xyz/UVA-React#47]
When changing from component, the first time a new route is entered it shows 'node was deleted'. It only works after going back and than reopening the component

## How we do it now
- Preact router

## Why does this need improving.
- Items depending on props won't work first render.
- Issue #46 might be related to this

## What would we need to change.
- Switching to React Router might solve this issue, this will need some more investigating to determine for certain.

## Which files are affected.
- src/routes/measurement/index.js
- src/routes/media/index.js
- src/routes/account/index.js
-

## Error messages if available
![screen shot 2018-01-18 at 18 30 06](https://user-images.githubusercontent.com/19853448/35112309-f10b00c2-fc7d-11e7-9da0-6fafe2859af8.png)

## Ways to reproduce this issue
- Go to overview
- Go to account 
- Graph will not load. (showing data is not loading properly).
- Open react-devtools
- Where the component should be it will say 'Node was removed'
- Going back and then going back to the component will cause it to render properly

## Temporary Quick Fix 
For this issue we need a temporarily for the product to function properly in tommorows demo.
Suggested quickfix:
- Load the measurements direct inside of the component.
- This will force the data to refetch from firebase on every route change.
This however will increase loading times and make our code less DRY.
A long term solution should be made ASAP.

## Estimated time needed to change.
Fixing this issue will proberly take arround 2 to 6 hours

**Comment by ThijsvanRijn** [comment]
Yannick are you there? We need you in Discord!
